#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="traefik-cert-dumper"

output_off
### Check to see if Enabled/Disabled

if [ "$ENABLE_CERTIFICATE_DUMPER" = "FALSE" ] || [ "$ENABLE_CERTIFICATE_DUMPER" = "false" ] || [ "$ENABLE_LETSENCRYPT" = "FALSE" ] || [ "$ENABLE_LETSENCRYPT" = "false" ]; then
    print_notice "Disabling Certificate Dumper Functionality"
    service_stop `basename $0`
fi

output_on
liftoff
