#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single

PROCESS_NAME="traefik"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting traefik ${TRAEFIK_VERSION}"
exec traefik -c /traefik/config/${CONFIG_FILE}
