#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service both
PROCESS_NAME="traefik"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting traefik ${TRAEFIK_VERSION}"
exec traefik --configfile ${TRAEFIK_CONFIG_PATH}${TRAEFIK_CONFIG_FILE}
