#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service both
PROCESS_NAME="traefik"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting traefik ${TRAEFIK_VERSION}"
if [ "${LOG_TYPE}" = "file" ] ; then silent_arg="silent" ; fi
${silent_arg} s6-setuidgid traefik exec traefik \
                                    --configfile "${CONFIG_PATH}"/"${CONFIG_FILE}" ${TRAEFIK_ARGS}
