services:

  traefik-app:
    image: docker.io/nfrastack/traefik:3.7
    container_name: traefik-app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=America/Vancouver
    networks:
      - proxy
    restart: always

  whoami:
    container_name: whoami
    image: containous/whoami:v1.3.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=HostRegexp(`whoam[i|i2).example.(com|.org)`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
