#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="traefik"

check_container_initialized
check_service_initialized init

CONFIG_FILE=${CONFIG_FILE:-"config.toml"}
liftoff

print_info "Starting traefik ${TRAEFIK_VERSION}"
exec traefik -c /traefik/config/${CONFIG_FILE}
