#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="traefik"
check_initialized

CONFIG_FILE=${CONFIG_FILE:-"config.toml"}
liftoff

print_info "Starting traefik ${TRAEFIK_VERSION}"
exec traefik -c /traefik/config/${CONFIG_FILE}
